more fixes for CircleCI API publish config
Signed-off-by: Ben Burns <803016+benjamincburns@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -271,7 +271,7 @@ jobs:
   publishAPIDoc:
     executor: small_executor
     steps:
-#      - prepare
+      - prepare
 #      - run:
 #          name: Build runnable Teku binaries
 #          command: |
@@ -293,20 +293,18 @@ jobs:
       - run:
           name: Deploy to GitHub Pages
           command: |
-            readonly GIT_URL="git@github.com:$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git"
-            readonly COMMIT="$(git rev-parse --short HEAD)"
             readonly BRANCH='gh-pages-test-do-not-remove-yet'
 
             echo "Debugging env vars:"
-            echo "GIT_URL=$GIT_URL"
-            echo "COMMIT=$COMMIT"
             echo "BRANCH=$BRANCH"
 
-            git clone --depth=1 "$GIT_URL" -b "$BRANCH" "$BRANCH"
-            cd "$BRANCH"
+            git checkout "$BRANCH" || git checkout -b "$BRANCH"
+            # pull might fail if the branch was just created
+            git pull || true
+
             touch testfile.txt
             git add --all
-            git commit -m "[skip ci] test" || true
+            git commit -m "[skip ci] test"
             git push origin "$BRANCH"
 workflows:
   version: 2
