Fix paths used to determine split of reference tests across executors.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -243,14 +243,19 @@ jobs:
           name: ReferenceTests
           no_output_timeout: 30m
           command: |
-            CLASSNAMES=$(circleci tests glob "**/src/referenceTest/generated/**/*Test.java" \
-              | sed 's@.*/src/referenceTest/generated/@@' \
+            CLASSNAMES=$(circleci tests glob "**/src/referenceTest/generated_tests/**/*Test.java" \
+              | sed 's@.*/src/referenceTest/generated_tests/@@' \
               | sed 's@/@.@g' \
               | sed 's/.\{5\}$//' \
               | circleci tests split --split-by=timings --timings-type=classname)
             # Format the arguments to "./gradlew test"
             GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
             echo "Prepared arguments for Gradle: $GRADLE_ARGS"
+            if [[ -z "$GRADLE_ARGS" ]]
+            then
+              echo "Failed to determine correct distribution of tests across nodes"
+              exit 1
+            fi
             ./gradlew --no-daemon --parallel -x generateReferenceTestClasses -x processReferenceTestResources -x cleanReferenceTestClasses referenceTest $GRADLE_ARGS
       - capture_test_results
 
