Reduce executor count as referenceTests are no longer the longest task.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -158,6 +158,11 @@ jobs:
             # Format the arguments to "./gradlew test"
             GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
             echo "Prepared arguments for Gradle: $GRADLE_ARGS"
+            if [[ -z "$GRADLE_ARGS" ]]
+            then
+              echo "Failed to determine correct distribution of tests across nodes"
+              exit 1
+            fi
             ./gradlew --no-daemon --parallel test $GRADLE_ARGS
       - capture_test_results
 
@@ -194,6 +199,11 @@ jobs:
             # Format the arguments to "./gradlew test"
             GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
             echo "Prepared arguments for Gradle: $GRADLE_ARGS"
+            if [[ -z "$GRADLE_ARGS" ]]
+            then
+              echo "Failed to determine correct distribution of tests across nodes"
+              exit 1
+            fi
             ./gradlew --no-daemon --parallel acceptanceTest $GRADLE_ARGS
       - capture_test_results
       - capture_test_artifacts
@@ -233,7 +243,7 @@ jobs:
             - ./eth-reference-tests/
 
   referenceTests:
-    parallelism: 7
+    parallelism: 5
     executor: large_executor
     steps:
       - prepare
