ref tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,6 +2,7 @@
 name: ci
 
 # Circle
+# https://app.circleci.com/pipelines/github/Consensys/teku/38576/workflows/4aac2ddd-0cbd-4d9c-9285-e49f911411d0
 # https://circleci.com/pricing/price-list/
 # medium   2    4
 # medium+  3    6
@@ -46,10 +47,8 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         submodules: 'recursive'
-
   #     - name: Prepare
   #       uses: ./.github/actions/prepare
-
   #     - name: Spotless
   #       run: |
   #         ./gradlew spotlessCheck
@@ -64,10 +63,8 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         submodules: 'recursive'
-
   #     - name: Prepare
   #       uses: ./.github/actions/prepare
-
   #     - name: Check modules
   #       run: |
   #         ./gradlew checkMavenCoordinateCollisions checkModuleDependencies
@@ -83,23 +80,19 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         submodules: 'recursive'
-
   #     - name: Prepare
   #       uses: ./.github/actions/prepare
-
   #     - name: Build
   #       shell: powershell
   #       run: |
   #         $Env:JAVA_TOOL_OPTIONS = "-Xmx2g"
   #         $Env:GRADLE_OPTS = "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.vfs.watch=false"
   #         cmd.exe /c gradlew.bat --no-daemon --parallel --build-cache
-      
   #     - name: Build
   #       shell: powershell
   #       run: |
   #         New-Item -ItemType Directory -Force build\test-results
   #         Get-ChildItem -Recurse | Where-Object {$_.FullName -match "test-results\\.*\\.*.xml"} | Copy-Item -Destination build\test-results\
-
   #     - name: Publish Windows Test Results and Reports
   #       uses: actions/upload-artifact@v4
   #       if: always()
@@ -116,34 +109,31 @@ jobs:
     runs-on: ubuntu-24.04
     environment: dev
     outputs:
-      workflow_run_id: ${{ steps.workflowdetails.outputs.id }}    
+      workflow_run_id: ${{ steps.workflowdetails.outputs.run_id }}    
     steps:
       - name: Checkout
         uses: actions/checkout@v5
         with:
           submodules: 'recursive'
-
       - name: get workflow_details
         id: workflowdetails
-        shell: bash      
+        shell: bash
         run: |
-          echo "id=${{ github.run_id }}" >> $GITHUB_OUTPUT
+          echo "run_id=${{ github.run_id }}" >> $GITHUB_OUTPUT
           echo "build_date=$(date --rfc-3339=date)" >> $GITHUB_OUTPUT
-    
       - name: Prepare
         uses: ./.github/actions/prepare
-            
       - name: Assemble
+        shell: bash      
         run: |
           ./gradlew clean compileJava compileTestJava compileJmhJava compileIntegrationTestJava compileAcceptanceTestJava compilePropertyTestJava assemble
-
-    # TODO: check why this is done
-    #   - run:
-    #       name: Prep Artifacts
-    #       command: |
-    #         mkdir /tmp/teku-distributions
-    #         cp build/distributions/*.tar.gz /tmp/teku-distributions/
-
+      - name: Upload distribution
+        uses: actions/upload-artifact@v4
+        with:
+          name: distribution
+          path: |
+            build/distributions/*.tar.gz
+          retention-days: 28
       - name: Upload workspace build
         uses: actions/upload-artifact@v4
         with:
@@ -153,114 +143,89 @@ jobs:
             !./.git/**
           retention-days: 1
 
-  unitTests:
-    # circle large 4/16 PARALLEL      = 8m
-    # gha ubuntu-latest-128 32/128    = 4m
-    # gha-runner-scale-set-ubuntu-22.04-amd64-large  = 6m
-    needs: assemble
-    uses: ./.github/workflows/matrix-tests-template.yml
-    with:
-      assemble_output_run_id: ${{ github.run_id }}
-      stage_name: Unit Tests
-      stage_key: unit
-      gradle_task: test
-      src_pattern: "*/src/test/java/*"
-      src_root: "src/test/java"
-      runner: "gha-runner-scale-set-ubuntu-22.04-amd64-large"
+  ## OpenAPI spec
+  # 6m
+  # extractAPISpec:
+  #   needs: assemble
+  #   runs-on: ubuntu-24.04
+  #   environment: dev
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v5
+  #       with:
+  #         submodules: 'recursive'
+  #     - name: Prepare
+  #       uses: ./.github/actions/prepare
+  #     - name: Download assemble-output
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         github-token: ${{ github.token }}
+  #         repository: ${{ github.repository }}
+  #         run-id: ${{ github.run_id }}
+  #         name: assemble-output
+  #         merge-multiple: true            
+  #     - name: Build runnable Teku binaries
+  #       shell: bash
+  #       run: |
+  #         ./gradlew --no-daemon --parallel installDist
+  #     - name: Build runnable Teku binaries
+  #       shell: bash
+  #       run: |
+  #         mkdir -p .openapidoc/spec
 
-  unitTestsReport:
-    runs-on: ubuntu-latest
-    needs: unitTests
-    if: always()
-    steps:
-      - uses: actions/checkout@v5
-      - uses: ./.github/actions/junit-reports
-        if: always()        
-        with:
-          stage_key: unit
+  #         build/install/teku/bin/teku --network=mainnet --ee-endpoint=unsafe-test-stub --ignore-weak-subjectivity-period-enabled --Xinterop-enabled=true --rest-api-enabled=true --rest-api-docs-enabled=true 2>&1 > teku_output.log &
+  #         TEKU_PID=$!
 
-  integrationTests:
-    # circle large 4/16 PARALLEL      = 18m
-    # gha ubuntu-latest-128 32/64     = 16m
-    needs: assemble
-    runs-on: ubuntu-latest-128
-    environment: dev
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v5
-        with:
-          submodules: 'recursive'
+  #         EXIT_CODE=0
+  #         wget --timeout=30 --retry-connrefused --output-document=.openapidoc/spec/teku.json http://localhost:5051/swagger-docs
+  #         if [ $? != 0 ]; then
+  #           EXIT_CODE=1
+  #         fi
 
-      - name: Prepare
-        uses: ./.github/actions/prepare
+  #         kill $TEKU_PID
+  #         exit $EXIT_CODE
+  #     - name: Upload openapi spec
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: openapi-spec
+  #         path: |
+  #           .openapidoc/spec/teku.json
+  #         retention-days: 7
 
-      - name: Download assemble-output
-        uses: actions/download-artifact@v4
-        with:
-          name: assemble-output
+  # TODO: 
+  # publishAPISpec:
+  
+  ## Tests 
+  # unitTests:
+  #   # circle large 4/16 PARALLEL      = 8m
+  #   # gha ubuntu-latest-128 32/128    = 4m
+  #   # gha-runner-scale-set-ubuntu-22.04-amd64-large  = 6m
+  #   needs: assemble
+  #   uses: ./.github/workflows/matrix-tests-template.yml
+  #   secrets: inherit  
+  #   with:
+  #     assemble_output_run_id: ${{ github.run_id }}
+  #     stage_name: Unit Tests
+  #     stage_key: unit
+  #     gradle_task: test
+  #     src_pattern: "*/src/test/java/*"
+  #     src_root: "src/test/java"
+  #     runner: "gha-runner-scale-set-ubuntu-22.04-amd64-large"
 
-      - name: Integration Tests
-        run: |
-          ./gradlew integrationTest
+  # unitTestsReport:
+  #   runs-on: ubuntu-latest
+  #   needs: unitTests
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #     - uses: ./.github/actions/junit-reports
+  #       if: always()        
+  #       with:
+  #         stage_key: unit
 
-      - name: Test results 
-        uses: ./.github/actions/test-results
-        if: always()        
-        with:
-          stage_key: 'integration'
-
-  propertyTests:
-    # circle medium_plus_executor 4/16 PARALLEL = 30m
-    # gha-runner-scale-set-ubuntu-22.04-amd64-large = 13m  8/64                           
-    needs: assemble
-    uses: ./.github/workflows/matrix-tests-template.yml
-    with:
-      assemble_output_run_id: ${{ github.run_id }}
-      stage_name: Property Tests
-      stage_key: property
-      gradle_task: propertyTest
-      src_pattern: "*/src/property-test/java/*"
-      src_root: "src/property-test/java"
-      runner: "gha-runner-scale-set-ubuntu-22.04-amd64-xl"
-
-  propertyTestsReport:
-    runs-on: ubuntu-latest
-    needs: propertyTests
-    if: always()
-    steps:
-      - uses: actions/checkout@v5
-      - uses: ./.github/actions/junit-reports
-        if: always()        
-        with:
-          stage_key: property
-
-  acceptanceTests:
-    # circle large 4/16 PARALLEL        = 12m
-    # gha ubuntu-latest-128 32/64  
-    needs: assemble
-    uses: ./.github/workflows/matrix-tests-template.yml    
-    with:
-      assemble_output_run_id: ${{ github.run_id }}
-      stage_name: Acceptance Tests
-      stage_key: acceptance
-      gradle_task: acceptanceTest
-      src_pattern: "*/src/acceptance-test/java/*"
-      src_root: "src/acceptance-test/java"
-      runner: "gha-runner-scale-set-ubuntu-22.04-amd64-xxl"
-
-  acceptanceTestsReport:
-    runs-on: ubuntu-latest
-    needs: acceptanceTests
-    if: always()
-    steps:
-      - uses: actions/checkout@v5
-      - uses: ./.github/actions/junit-reports
-        if: always()        
-        with:
-          stage_key: acceptance
-
-
-  # referenceTests:
+  # integrationTests:
+  #   # circle large 4/16 PARALLEL      = 18m
+  #   # gha ubuntu-latest-128 32/64     = 16m
   #   needs: assemble
   #   runs-on: ubuntu-latest-128
   #   environment: dev
@@ -269,53 +234,197 @@ jobs:
   #       uses: actions/checkout@v5
   #       with:
   #         submodules: 'recursive'
-
   #     - name: Prepare
   #       uses: ./.github/actions/prepare
-
-  #     - name: Download workspace build
+  #     - name: Download assemble-output
   #       uses: actions/download-artifact@v4
   #       with:
-  #         name: workspace
-
-  #     - name: Fetch Reference Tests
+  #         name: assemble-output
+  #     - name: Integration Tests
   #       run: |
-  #         if [ ! -d "eth-reference-tests/src/referenceTest/resources/consensus-spec-tests/tests" ]
-  #         then
-  #           ./gradlew --no-daemon expandRefTests
-  #         fi
-
-  #     - name: Compile Reference Tests
-  #       run: |
-  #         ./gradlew --no-daemon --parallel compileReferenceTestJava
-
-  #     - name: Reference Tests      
-  #       run: |
-  #         ./gradlew -x generateReferenceTestClasses -x processReferenceTestResources -x cleanReferenceTestClasses referenceTest
-
+  #         ./gradlew integrationTest
   #     - name: Test results 
-  #       uses: ./.github/actions/testResults
+  #       uses: ./.github/actions/test-results
   #       if: always()        
   #       with:
-  #         suiteName: 'referenceTests'
+  #         stage_key: 'integration'
 
-  # ========== GLOBAL ROLL-UP ==========
-  collatedTestsReport:
-    runs-on: ubuntu-latest
-    needs:
-      - unitTests
-      - propertyTests
-      - acceptanceTests
+  # propertyTests:
+  #   # circle medium_plus_executor 4/16 PARALLEL = 30m
+  #   # gha-runner-scale-set-ubuntu-22.04-amd64-large = 13m  8/64                           
+  #   needs: assemble
+  #   uses: ./.github/workflows/matrix-tests-template.yml
+  #   secrets: inherit
+  #   with:
+  #     assemble_output_run_id: ${{ github.run_id }}
+  #     stage_name: Property Tests
+  #     stage_key: property
+  #     gradle_task: propertyTest
+  #     src_pattern: "*/src/property-test/java/*"
+  #     src_root: "src/property-test/java"
+  #     runner: "gha-runner-scale-set-ubuntu-22.04-amd64-xl"
 
-    if: always()
+  # propertyTestsReport:
+  #   runs-on: ubuntu-latest
+  #   needs: propertyTests
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #     - uses: ./.github/actions/junit-reports
+  #       if: always()        
+  #       with:
+  #         stage_key: property
+
+  # acceptanceTests:
+  #   # circle large 4/16 PARALLEL        = 12m
+  #   # gha ubuntu-latest-128 32/64  
+  #   needs: assemble
+  #   uses: ./.github/workflows/matrix-tests-template.yml
+  #   secrets: inherit
+  #   with:
+  #     assemble_output_run_id: ${{ github.run_id }}
+  #     stage_name: Acceptance Tests
+  #     stage_key: acceptance
+  #     gradle_task: acceptanceTest
+  #     src_pattern: "*/src/acceptance-test/java/*"
+  #     src_root: "src/acceptance-test/java"
+  #     runner: "gha-runner-scale-set-ubuntu-22.04-amd64-xxl"
+
+  # acceptanceTestsReport:
+  #   runs-on: ubuntu-latest
+  #   needs: acceptanceTests
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #     - uses: ./.github/actions/junit-reports
+  #       if: always()        
+  #       with:
+  #         stage_key: acceptance
+
+  referenceTestsPrep:
+    needs: assemble
+    runs-on: ubuntu-24.04
+    environment: dev
     steps:
-      - uses: actions/checkout@v5
-      - uses: actions/download-artifact@v4
+      - name: Checkout
+        uses: actions/checkout@v5
         with:
-          path: reports
-      - name: All Tests (Combined)
-        uses: dorny/test-reporter@v1
+          submodules: 'recursive'
+      - name: Prepare
+        uses: ./.github/actions/prepare
+      - name: Download assemble-output
+        uses: actions/download-artifact@v4
         with:
-          name: All Tests (Unit + Property + Integration + Acceptance)
-          path: "reports/**/TEST-*.xml"
-          reporter: java-junit
+          github-token: ${{ github.token }}
+          repository: ${{ github.repository }}
+          run-id: ${{ github.run_id }}
+          name: assemble-output
+          merge-multiple: true
+      - uses: actions/cache/restore@v4
+        with:
+          path: eth-reference-tests/src/referenceTest/resources/consensus-spec-tests/
+          key: reftests-${{ hashFiles('build.gradle') }} 
+      - name: FetchReferenceTests
+        shell: bash
+        run: |
+          if [ ! -d "eth-reference-tests/src/referenceTest/resources/consensus-spec-tests/tests" ]
+          then
+            ./gradlew --no-daemon expandRefTests
+          fi
+      - name: CompileReferenceTests
+        # Compile separately so that we have the generated test files for splitting across nodes
+        shell: bash
+        run: |
+          ./gradlew --no-daemon --parallel compileReferenceTestJava
+      - name: Caching reference tests 
+        uses: actions/cache/save@v4
+        with:
+          path: eth-reference-tests/src/referenceTest/resources/consensus-spec-tests/
+          key: reftests-${{ hashFiles('build.gradle') }}
+      - name: Upload reftests
+        uses: actions/upload-artifact@v4
+        with:
+          name: reftests
+          path: |
+            ./eth-reference-tests/
+          retention-days: 1
+
+  referenceTestsManual:
+    needs: referenceTestsPrep
+    runs-on: ubuntu-24.04
+    environment: dev
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
+        with:
+          submodules: 'recursive'
+
+      - name: Download assemble-output
+        uses: actions/download-artifact@v4
+        with:
+          github-token: ${{ github.token }}
+          repository: ${{ github.repository }}
+          run-id: ${{ github.run_id }}
+          name: assemble-output
+          merge-multiple: true
+
+      - name: Download reftests-prep (optional)
+        uses: actions/download-artifact@v4
+        with:
+          github-token: ${{ github.token }}
+          repository: ${{ github.repository }}
+          run-id: ${{ github.run_id }}
+          name: reftests
+          merge-multiple: true
+
+      - name: Prepare
+        uses: ./.github/actions/prepare
+
+      - shell: bash
+        run: |
+          tree .
+          
+
+  referenceTests:
+    needs: referenceTestsPrep
+    uses: ./.github/workflows/matrix-tests-template.yml
+    secrets: inherit    
+    with:
+      assemble_output_run_id: ${{ github.run_id }}
+      stage_name: Reference Tests
+      stage_key: reference
+      gradle_task: "-x generateReferenceTestClasses -x processReferenceTestResources -x cleanReferenceTestClasses referenceTest"
+      src_pattern: "*/src/referenceTest/generated_tests/**/*Test.java"
+      src_root: "src/referenceTest/generated_tests"
+      runner: "ubuntu-latest-128"
+
+  # referenceTestsReport:
+  #   runs-on: ubuntu-latest
+  #   needs: referenceTests
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #     - uses: ./.github/actions/junit-reports
+  #       if: always()
+  #       with:
+  #         stage_key: reference
+
+  # # ========== GLOBAL ROLL-UP ==========
+  # collatedTestsReport:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - unitTests
+  #     - propertyTests
+  #     - acceptanceTests
+  #   if: always()
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #     - uses: actions/download-artifact@v4
+  #       with:
+  #         path: reports
+  #     - name: All Tests (Combined)
+  #       uses: dorny/test-reporter@v1
+  #       with:
+  #         name: All Tests (Unit + Property + Integration + Acceptance)
+  #         path: "reports/**/TEST-*.xml"
+  #         reporter: java-junit
