run integration tests in matrices

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -290,37 +290,41 @@ jobs:
 
   integrationTests:
     needs: assemble
-    runs-on: gha-runner-scale-set-ubuntu-22.04-amd64-xxl
+    uses: ./.github/workflows/matrix-tests-template.yml
+    secrets: inherit
+    with:
+      assemble_output_run_id: ${{ github.run_id }}
+      stage_name: Integration Tests
+      stage_key: integration
+      gradle_task: integrationTest
+      src_pattern: "*/src/integration-test/java/*"
+      src_root: "src/integration-test/java"
+      runner: "gha-runner-scale-set-ubuntu-22.04-amd64-large"
+
+  integrationTestsResult:
+    runs-on: ubuntu-24.04
+    needs: integrationTests
+    if: always()
     steps:
-      - name: Checkout
-        uses: actions/checkout@v5
-        with:
-          submodules: 'recursive'
-      - name: Prepare
-        uses: ./.github/actions/prepare
-      - name: Download assemble-output
-        uses: actions/download-artifact@v7
-        with:
-          name: assemble-output
-          path: ${{ github.workspace }}   
-      - name: Integration Tests
-        run: |
-          ./gradlew integrationTest
-      - name: Upload JUnit XML + HTML for integration-tests
+      - run: |
+          echo "integrationTests result: ${{ needs.integrationTests.result }}"
+          if [ "${{ needs.integrationTests.result }}" != "success" ]; then
+            echo "❌ One or more integrationTests matrix jobs failed."
+            exit 1
+          fi
+          echo "✅ All integrationTests matrix jobs passed."
+
+  integrationTestsReport:
+    runs-on: ubuntu-24.04
+    needs: integrationTests
+    if: always()
+    steps:
+      - uses: actions/checkout@v5
+      - uses: ./.github/actions/collate-junit-reports
+        continue-on-error: true
         if: always()
-        uses: actions/upload-artifact@v6
         with:
-          name: integration-reports-unified
-          path: |
-            **/build/test-results/**/TEST-*.xml
-            **/build/reports/tests/**
-          if-no-files-found: ignore
-          retention-days: 1          
-      - name: Test results 
-        uses: ./.github/actions/collate-junit-reports
-        if: always()        
-        with:
-          stage_key: 'integration'
+          stage_key: integration
 
   propertyTests:
     needs: assemble
